spin_manifest_version = 2

[application]
name = "spin-app"
version = "0.1.0"
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin-app"

[component.spin-app]
source = "service.wasm"
allowed_outbound_hosts = []
[component.spin-app.build]
command = "cargo component build && cargo component build --manifest-path ../business-logic/Cargo.toml && wasm-tools compose target/wasm32-wasi/debug/spinhttpcomponent.wasm -d ../business-logic/target/wasm32-wasi/debug/businesslogic.wasm -o service.wasm"
